export interface articleInterface {
  id: number;
  title: string;
  dueDate: string;
  category: string;
  status: string;
  assignedTo: string;
  image: string;
  logo: string;
  attachments: number;
};

export const articles: articleInterface[] = [
    {
      id: 1,
      title: 'Significant Deficiencies in Internal Control Procedures, Increasing...',
      dueDate: '2023-12-10',
      category: 'Health & Safety',
      status: 'Open',
      assignedTo: 'Simon Bell',
      image: '/banner1.jpeg',
      logo: '/logo-icon.png',
      attachments: 2,
    },
    {
      id: 2,
      title: 'Lack of Compliance with Safety Regulations in Construction Site',
      dueDate: '2023-11-25',
      category: 'Compliance',
      status: 'In Progress',
      assignedTo: 'Jessica Adams',
      image: '/banner1.jpeg',
      logo: '/logo-icon.png',
      attachments: 1,
    },
    {
      id: 3,
      title: 'Review and Update of Emergency Evacuation Plan',
      dueDate: '2023-12-01',
      category: 'Health & Safety',
      status: 'Completed',
      assignedTo: 'John Smith',
      image: '/banner2.jpg',
      logo: '/logo-icon.png',
      attachments: 3,
    },
    {
      id: 4,
      title: 'Fire Safety Equipment Maintenance Schedule Overdue',
      dueDate: '2023-12-05',
      category: 'Maintenance',
      status: 'Drafted',
      assignedTo: 'Oliver Brown',
      image: '/banner1.jpeg',
      logo: '/logo-icon.png',
      attachments: 0,
    },
    {
      id: 5,
      title: 'Improvement in Data Security Protocols Required',
      dueDate: '2023-11-20',
      category: 'IT & Data Security',
      status: 'Open',
      assignedTo: 'Emma Davis',
      image: '/banner2.jpg',
      logo: '/logo-icon.png',
      attachments: 5,
    },
    {
      id: 6,
      title: 'Failure to Conduct Monthly Safety Inspections',
      dueDate: '2023-12-15',
      category: 'Health & Safety',
      status: 'In Progress',
      assignedTo: 'Simon Bell',
      image: '/banner2.jpg',
      logo: '/logo-icon.png',
      attachments: 2,
    },
    {
      id: 7,
      title: 'Lack of Personal Protective Equipment Availability',
      dueDate: '2023-12-02',
      category: 'Health & Safety',
      status: 'Drafted',
      assignedTo: 'Lily Thompson',
      image: '/banner1.jpeg',
      logo: '/logo-icon.png',
      attachments: 1,
    },
    {
      id: 8,
      title: 'Quarterly Financial Audit Due',
      dueDate: '2023-12-20',
      category: 'Finance',
      status: 'Completed',
      assignedTo: 'Peter Johnson',
      image: '/banner2.jpg',
      logo: '/logo-icon.png',
      attachments: 4,
    },
    {
      id: 9,
      title: 'Non-compliance with Environmental Regulations',
      dueDate: '2023-11-30',
      category: 'Compliance',
      status: 'Open',
      assignedTo: 'Sarah Wilson',
      image: '/banner2.jpg',
      logo: '/logo-icon.png',
      attachments: 3,
    },
    {
      id: 10,
      title: 'Cybersecurity Training for Employees Overdue',
      dueDate: '2023-12-18',
      category: 'IT & Data Security',
      status: 'In Progress',
      assignedTo: 'Ethan White',
      image: '/banner1.jpeg',
      logo: '/logo-icon.png',
      attachments: 0,
    },
    {
      id: 11,
      title: 'Safety Procedures for Hazardous Materials Handling',
      dueDate: '2023-12-14',
      category: 'Health & Safety',
      status: 'Open',
      assignedTo: 'Sophia Green',
      image: '/banner1.jpeg',
      logo: '/logo-icon.png',
      attachments: 1,
    },
    {
      id: 12,
      title: 'Internal Audit of Workplace Safety Practices',
      dueDate: '2023-12-28',
      category: 'Audit',
      status: 'Completed',
      assignedTo: 'David Clark',
      image: '/banner1.jpeg',
      logo: '/logo-icon.png',
      attachments: 2,
    },
    {
      id: 13,
      title: 'Training Program on New Equipment Use Required',
      dueDate: '2023-12-12',
      category: 'Training',
      status: 'In Progress',
      assignedTo: 'Mia Baker',
      image: '/banner1.jpeg',
      logo: '/logo-icon.png',
      attachments: 3,
    },
    {
      id: 14,
      title: 'Update of IT Security Policies Due',
      dueDate: '2023-11-29',
      category: 'IT & Data Security',
      status: 'Open',
      assignedTo: 'Daniel Moore',
      image: '/banner1.jpeg',
      logo: '/logo-icon.png',
      attachments: 1,
    },
    {
      id: 15,
      title: 'Annual Review of Environmental Sustainability Plan',
      dueDate: '2023-12-16',
      category: 'Environment',
      status: 'Drafted',
      assignedTo: 'Sophia Scott',
      image: '/banner1.jpeg',
      logo: '/logo-icon.png',
      attachments: 0,
    },
    {
      id: 16,
      title: 'Inspection of Electrical Systems for Safety Concerns',
      dueDate: '2023-12-09',
      category: 'Maintenance',
      status: 'Completed',
      assignedTo: 'Benjamin King',
      image: '/banner1.jpeg',
      logo: '/logo-icon.png',
      attachments: 2,
    },
    {
      id: 17,
      title: 'Monthly Health & Safety Committee Meeting',
      dueDate: '2023-12-13',
      category: 'Health & Safety',
      status: 'Open',
      assignedTo: 'Chloe Martinez',
      image: '/banner1.jpeg',
      logo: '/logo-icon.png',
      attachments: 3,
    },
    {
      id: 18,
      title: 'Preparation of Year-End Financial Statements',
      dueDate: '2023-12-22',
      category: 'Finance',
      status: 'Drafted',
      assignedTo: 'Lucas Taylor',
      image: '/banner1.jpeg',
      logo: '/logo-icon.png',
      attachments: 1,
    },
    {
      id: 19,
      title: 'Emergency Response Plan Review',
      dueDate: '2023-12-07',
      category: 'Health & Safety',
      status: 'Completed',
      assignedTo: 'Amelia Walker',
      image: '/banner2.jpg',
      logo: '/logo-icon.png',
      attachments: 4,
    },
    {
      id: 20,
      title: 'Scheduled Review of Vendor Contracts',
      dueDate: '2023-12-17',
      category: 'Legal',
      status: 'In Progress',
      assignedTo: 'Mason Harris',
      image: '/banner1.jpeg',
      logo: '/logo-icon.png',
      attachments: 0,
    },
        {
          id: 21,
          title: 'Review of Employee Training Records',
          dueDate: '2023-11-26',
          category: 'Training',
          status: 'Open',
          assignedTo: 'Grace Nelson',
          image: '/banner1.jpeg',
          logo: '/logo-icon.png',
          attachments: 2,
        },
        {
          id: 22,
          title: 'Compliance Check for New Regulations',
          dueDate: '2023-12-04',
          category: 'Compliance',
          status: 'In Progress',
          assignedTo: 'Samuel Young',
          image: '/banner2.jpg',
          logo: '/logo-icon.png',
          attachments: 1,
        },
        {
          id: 23,
          title: 'Evaluation of Workplace Ergonomics',
          dueDate: '2023-12-11',
          category: 'Health & Safety',
          status: 'Completed',
          assignedTo: 'Ella Hill',
          image: '/banner1.jpeg',
          logo: '/logo-icon.png',
          attachments: 3,
        },
        {
          id: 24,
          title: 'Updating Fire Drill Procedures',
          dueDate: '2023-12-08',
          category: 'Health & Safety',
          status: 'Drafted',
          assignedTo: 'Nathan King',
          image: '/banner2.jpg',
          logo: '/logo-icon.png',
          attachments: 0,
        },
        {
          id: 25,
          title: 'Assessment of Cybersecurity Measures',
          dueDate: '2023-11-18',
          category: 'IT & Data Security',
          status: 'Open',
          assignedTo: 'Sofia Lee',
          image: '/banner1.jpeg',
          logo: '/logo-icon.png',
          attachments: 5,
        },
        {
          id: 26,
          title: 'Fire Safety Equipment Inspection',
          dueDate: '2023-11-30',
          category: 'Maintenance',
          status: 'In Progress',
          assignedTo: 'Lucas Scott',
          image: '/banner2.jpg',
          logo: '/logo-icon.png',
          attachments: 2,
        },
        {
          id: 27,
          title: 'Evaluation of Safety Gear Inventory',
          dueDate: '2023-12-21',
          category: 'Health & Safety',
          status: 'Completed',
          assignedTo: 'Emma Collins',
          image: '/banner1.jpeg',
          logo: '/logo-icon.png',
          attachments: 1,
        },
        {
          id: 28,
          title: 'Financial Reporting Standards Review',
          dueDate: '2023-12-19',
          category: 'Finance',
          status: 'Drafted',
          assignedTo: 'Jackson Reed',
          image: '/banner2.jpg',
          logo: '/logo-icon.png',
          attachments: 0,
        },
        {
          id: 29,
          title: 'Cybersecurity Policy Updates Needed',
          dueDate: '2023-12-30',
          category: 'IT & Data Security',
          status: 'In Progress',
          assignedTo: 'Mia Roberts',
          image: '/banner1.jpeg',
          logo: '/logo-icon.png',
          attachments: 3,
        },
        {
          id: 30,
          title: 'Weekly Safety Protocol Review',
          dueDate: '2023-11-27',
          category: 'Health & Safety',
          status: 'Open',
          assignedTo: 'Elijah Turner',
          image: '/banner2.jpg',
          logo: '/logo-icon.png',
          attachments: 2,
        },
        {
          id: 31,
          title: 'Workplace Hazard Identification Audit',
          dueDate: '2023-11-28',
          category: 'Audit',
          status: 'Completed',
          assignedTo: 'Ava Sanchez',
          image: '/banner1.jpeg',
          logo: '/logo-icon.png',
          attachments: 1,
        },
        {
          id: 32,
          title: 'Training on New Compliance Regulations',
          dueDate: '2023-12-03',
          category: 'Training',
          status: 'In Progress',
          assignedTo: 'William Parker',
          image: '/banner2.jpg',
          logo: '/logo-icon.png',
          attachments: 3,
        },
        {
          id: 33,
          title: 'Environmental Impact Assessment',
          dueDate: '2023-12-15',
          category: 'Environment',
          status: 'Open',
          assignedTo: 'Isabella Bennett',
          image: '/banner1.jpeg',
          logo: '/logo-icon.png',
          attachments: 4,
        },
        {
          id: 34,
          title: 'Safety Training for New Employees',
          dueDate: '2023-12-09',
          category: 'Training',
          status: 'Drafted',
          assignedTo: 'Oliver Gonzalez',
          image: '/banner2.jpg',
          logo: '/logo-icon.png',
          attachments: 0,
        },
        {
          id: 35,
          title: 'Review of First Aid Kits Availability',
          dueDate: '2023-12-12',
          category: 'Health & Safety',
          status: 'Completed',
          assignedTo: 'Aiden Hughes',
          image: '/banner1.jpeg',
          logo: '/logo-icon.png',
          attachments: 2,
        },
        // {
        //   id: 36,
        //   title: 'Assessment of Ergonomic Workstations',
        //   dueDate: '2023-12-29',
        //   category: 'Health & Safety',
        //   status: 'In Progress',
        //   assignedTo: 'Chloe Reed',
        //   image: '/banner2.jpg',
        //   logo: '/logo-icon.png',
        //   attachments: 1,
        // },
        // {
        //   id: 37,
        //   title: 'Annual Fire Safety Training',
        //   dueDate: '2023-12-26',
        //   category: 'Training',
        //   status: 'Open',
        //   assignedTo: 'James Wright',
        //   image: '/banner1.jpeg',
        //   logo: '/logo-icon.png',
        //   attachments: 5,
        // },
        // {
        //   id: 38,
        //   title: 'OSHA Compliance Review Scheduled',
        //   dueDate: '2023-11-22',
        //   category: 'Compliance',
        //   status: 'Drafted',
        //   assignedTo: 'Emily Diaz',
        //   image: '/banner2.jpg',
        //   logo: '/logo-icon.png',
        //   attachments: 0,
        // },
        // {
        //   id: 39,
        //   title: 'Quarterly Equipment Maintenance Check',
        //   dueDate: '2023-11-15',
        //   category: 'Maintenance',
        //   status: 'Completed',
        //   assignedTo: 'Henry Lee',
        //   image: '/banner1.jpeg',
        //   logo: '/logo-icon.png',
        //   attachments: 3,
        // },
        // {
        //   id: 40,
        //   title: 'Audit of Financial Records',
        //   dueDate: '2023-12-24',
        //   category: 'Finance',
        //   status: 'In Progress',
        //   assignedTo: 'Victoria Brown',
        //   image: '/banner2.jpg',
        //   logo: '/logo-icon.png',
        //   attachments: 2,
        // },
        // {
        //   id: 41,
        //   title: 'Review of Vendor Safety Protocols',
        //   dueDate: '2023-12-23',
        //   category: 'Compliance',
        //   status: 'Open',
        //   assignedTo: 'Liam Martinez',
        //   image: '/banner1.jpeg',
        //   logo: '/logo-icon.png',
        //   attachments: 4,
        // },
        // {
        //   id: 42,
        //   title: 'Update on Workplace Harassment Policies',
        //   dueDate: '2023-12-20',
        //   category: 'Legal',
        //   status: 'Drafted',
        //   assignedTo: 'Charlotte Hall',
        //   image: '/banner2.jpg',
        //   logo: '/logo-icon.png',
        //   attachments: 1,
        // },
        // {
        //   id: 43,
        //   title: 'Evaluation of Workplace Conditions',
        //   dueDate: '2023-11-14',
        //   category: 'Audit',
        //   status: 'Completed',
        //   assignedTo: 'Ryan White',
        //   image: '/banner1.jpeg',
        //   logo: '/logo-icon.png',
        //   attachments: 0,
        // },
        // {
        //   id: 44,
        //   title: 'Safety Inspection for Hazardous Areas',
        //   dueDate: '2023-12-25',
        //   category: 'Health & Safety',
        //   status: 'In Progress',
        //   assignedTo: 'Samantha King',
        //   image: '/banner2.jpg',
        //   logo: '/logo-icon.png',
        //   attachments: 3,
        // },
        // {
        //   id: 45,
        //   title: 'Review of Health Policies',
        //   dueDate: '2023-11-11',
        //   category: 'Health & Safety',
        //   status: 'Open',
        //   assignedTo: 'Avery Young',
        //   image: '/banner1.jpeg',
        //   logo: '/logo-icon.png',
        //   attachments: 1,
        // },
        // {
        //   id: 46,
        //   title: 'Training Needs Assessment',
        //   dueDate: '2023-12-06',
        //   category: 'Training',
        //   status: 'Drafted',
        //   assignedTo: 'Owen Martinez',
        //   image: '/banner2.jpg',
        //   logo: '/logo-icon.png',
        //   attachments: 5,
        // },
        // {
        //   id: 47,
        //   title: 'Assessment of Office Air Quality',
        //   dueDate: '2023-11-25',
        //   category: 'Environment',
        //   status: 'Completed',
        //   assignedTo: 'Emma Garcia',
        //   image: '/banner1.jpeg',
        //   logo: '/logo-icon.png',
        //   attachments: 2,
        // },
        // {
        //   id: 48,
        //   title: 'Evaluation of Emergency Response Procedures',
        //   dueDate: '2023-12-31',
        //   category: 'Health & Safety',
        //   status: 'In Progress',
        //   assignedTo: 'Zoe Carter',
        //   image: '/banner2.jpg',
        //   logo: '/logo-icon.png',
        //   attachments: 1,
        // },
        // {
        //   id: 49,
        //   title: 'Monthly Financial Review Meeting',
        //   dueDate: '2023-12-17',
        //   category: 'Finance',
        //   status: 'Open',
        //   assignedTo: 'Mason Wright',
        //   image: '/banner1.jpeg',
        //   logo: '/logo-icon.png',
        //   attachments: 4,
        // },
        // {
        //   id: 50,
        //   title: 'Compliance Training for New Employees',
        //   dueDate: '2023-12-03',
        //   category: 'Training',
        //   status: 'Drafted',
        //   assignedTo: 'Isabella Turner',
        //   image: '/banner2.jpg',
        //   logo: '/logo-icon.png',
        //   attachments: 2,
        // },
        // {
        //   id: 51,
        //   title: 'Audit of Safety Equipment',
        //   dueDate: '2023-12-18',
        //   category: 'Audit',
        //   status: 'In Progress',
        //   assignedTo: 'Aiden Thompson',
        //   image: '/banner1.jpeg',
        //   logo: '/logo-icon.png',
        //   attachments: 3,
        // },
        // {
        //   id: 52,
        //   title: 'Emergency Drill Preparation',
        //   dueDate: '2023-12-14',
        //   category: 'Health & Safety',
        //   status: 'Open',
        //   assignedTo: 'Sophie Taylor',
        //   image: '/banner2.jpg',
        //   logo: '/logo-icon.png',
        //   attachments: 0,
        // },
        // {
        //   id: 53,
        //   title: 'Safety Culture Assessment',
        //   dueDate: '2023-11-29',
        //   category: 'Health & Safety',
        //   status: 'Completed',
        //   assignedTo: 'Caleb Moore',
        //   image: '/banner1.jpeg',
        //   logo: '/logo-icon.png',
        //   attachments: 1,
        // },
        // {
        //   id: 54,
        //   title: 'Health and Safety Policy Review',
        //   dueDate: '2023-12-20',
        //   category: 'Compliance',
        //   status: 'Drafted',
        //   assignedTo: 'Chloe Robinson',
        //   image: '/banner2.jpg',
        //   logo: '/logo-icon.png',
        //   attachments: 2,
        // },
        // {
        //   id: 55,
        //   title: 'Review of Hazard Communication Program',
        //   dueDate: '2023-11-25',
        //   category: 'Audit',
        //   status: 'In Progress',
        //   assignedTo: 'David Lee',
        //   image: '/banner1.jpeg',
        //   logo: '/logo-icon.png',
        //   attachments: 0,
        // },
        // {
        //   id: 56,
        //   title: 'Evaluation of Workplace Safety Audits',
        //   dueDate: '2023-11-15',
        //   category: 'Audit',
        //   status: 'Open',
        //   assignedTo: 'Emma Davis',
        //   image: '/banner2.jpg',
        //   logo: '/logo-icon.png',
        //   attachments: 1,
        // },
        // {
        //   id: 57,
        //   title: 'Monthly Review of Safety Records',
        //   dueDate: '2023-12-12',
        //   category: 'Health & Safety',
        //   status: 'Completed',
        //   assignedTo: 'Samuel Walker',
        //   image: '/banner1.jpeg',
        //   logo: '/logo-icon.png',
        //   attachments: 2,
        // },
        // {
        //   id: 58,
        //   title: 'Quarterly Environmental Report',
        //   dueDate: '2023-12-28',
        //   category: 'Environment',
        //   status: 'In Progress',
        //   assignedTo: 'Sophia Allen',
        //   image: '/banner2.jpg',
        //   logo: '/logo-icon.png',
        //   attachments: 3,
        // },
        // {
        //   id: 59,
        //   title: 'Fire Safety Equipment Purchase Review',
        //   dueDate: '2023-12-05',
        //   category: 'Maintenance',
        //   status: 'Open',
        //   assignedTo: 'James Mitchell',
        //   image: '/banner1.jpeg',
        //   logo: '/logo-icon.png',
        //   attachments: 1,
        // },
        // {
        //   id: 60,
        //   title: 'Annual Workplace Safety Audit',
        //   dueDate: '2023-12-30',
        //   category: 'Audit',
        //   status: 'Drafted',
        //   assignedTo: 'Ella White',
        //   image: '/banner2.jpg',
        //   logo: '/logo-icon.png',
        //   attachments: 0,
        // },
        // {
        //   id: 61,
        //   title: 'Cybersecurity Risk Assessment',
        //   dueDate: '2023-11-10',
        //   category: 'IT & Data Security',
        //   status: 'Completed',
        //   assignedTo: 'Liam Brown',
        //   image: '/banner1.jpeg',
        //   logo: '/logo-icon.png',
        //   attachments: 3,
        // },
        // {
        //   id: 62,
        //   title: 'Emergency Preparedness Review',
        //   dueDate: '2023-12-11',
        //   category: 'Health & Safety',
        //   status: 'In Progress',
        //   assignedTo: 'Olivia Carter',
        //   image: '/banner2.jpg',
        //   logo: '/logo-icon.png',
        //   attachments: 2,
        // },
        // {
        //   id: 63,
        //   title: 'Safety Training for Office Staff',
        //   dueDate: '2023-12-09',
        //   category: 'Training',
        //   status: 'Open',
        //   assignedTo: 'Emma Lewis',
        //   image: '/banner1.jpeg',
        //   logo: '/logo-icon.png',
        //   attachments: 1,
        // },
        // {
        //   id: 64,
        //   title: 'Review of Injury Reporting Procedures',
        //   dueDate: '2023-11-22',
        //   category: 'Audit',
        //   status: 'Drafted',
        //   assignedTo: 'Daniel Walker',
        //   image: '/banner2.jpg',
        //   logo: '/logo-icon.png',
        //   attachments: 0,
        // },
        // {
        //   id: 65,
        //   title: 'Environmental Compliance Assessment',
        //   dueDate: '2023-12-18',
        //   category: 'Compliance',
        //   status: 'In Progress',
        //   assignedTo: 'Evelyn Scott',
        //   image: '/banner1.jpeg',
        //   logo: '/logo-icon.png',
        //   attachments: 3,
        // },
        // {
        //   id: 66,
        //   title: 'Annual Review of Health Policies',
        //   dueDate: '2023-12-01',
        //   category: 'Health & Safety',
        //   status: 'Completed',
        //   assignedTo: 'Alexander Young',
        //   image: '/banner2.jpg',
        //   logo: '/logo-icon.png',
        //   attachments: 2,
        // },
        // {
        //   id: 67,
        //   title: 'Quarterly Financial Compliance Review',
        //   dueDate: '2023-11-30',
        //   category: 'Finance',
        //   status: 'Open',
        //   assignedTo: 'Mia Rivera',
        //   image: '/banner1.jpeg',
        //   logo: '/logo-icon.png',
        //   attachments: 4,
        // },
        // {
        //   id: 68,
        //   title: 'Fire Safety Training for Staff',
        //   dueDate: '2023-11-15',
        //   category: 'Training',
        //   status: 'Drafted',
        //   assignedTo: 'Aiden Perez',
        //   image: '/banner2.jpg',
        //   logo: '/logo-icon.png',
        //   attachments: 0,
        // },
        // {
        //   id: 69,
        //   title: 'Review of First Aid Procedures',
        //   dueDate: '2023-12-05',
        //   category: 'Health & Safety',
        //   status: 'In Progress',
        //   assignedTo: 'Sophie Cooper',
        //   image: '/banner1.jpeg',
        //   logo: '/logo-icon.png',
        //   attachments: 1,
        // },
        // {
        //   id: 70,
        //   title: 'Annual Equipment Safety Review',
        //   dueDate: '2023-12-15',
        //   category: 'Maintenance',
        //   status: 'Open',
        //   assignedTo: 'James Taylor',
        //   image: '/banner2.jpg',
        //   logo: '/logo-icon.png',
        //   attachments: 5,
        // },
        // {
        //   id: 71,
        //   title: 'Review of Incident Reports',
        //   dueDate: '2023-12-22',
        //   category: 'Compliance',
        //   status: 'Drafted',
        //   assignedTo: 'Victoria Green',
        //   image: '/banner1.jpeg',
        //   logo: '/logo-icon.png',
        //   attachments: 2,
        // },
        // {
        //   id: 72,
        //   title: 'Assessment of Safety Training Programs',
        //   dueDate: '2023-12-01',
        //   category: 'Training',
        //   status: 'Completed',
        //   assignedTo: 'David Wilson',
        //   image: '/banner2.jpg',
        //   logo: '/logo-icon.png',
        //   attachments: 3,
        // },
        // {
        //   id: 73,
        //   title: 'Environmental Policy Updates',
        //   dueDate: '2023-12-26',
        //   category: 'Environment',
        //   status: 'In Progress',
        //   assignedTo: 'Avery Martinez',
        //   image: '/banner1.jpeg',
        //   logo: '/logo-icon.png',
        //   attachments: 0,
        // },
        // {
        //   id: 74,
        //   title: 'Audit of Environmental Procedures',
        //   dueDate: '2023-11-30',
        //   category: 'Audit',
        //   status: 'Open',
        //   assignedTo: 'Nolan Taylor',
        //   image: '/banner2.jpg',
        //   logo: '/logo-icon.png',
        //   attachments: 1,
        // },
        // {
        //   id: 75,
        //   title: 'Preparation of Health & Safety Reports',
        //   dueDate: '2023-12-21',
        //   category: 'Health & Safety',
        //   status: 'In Progress',
        //   assignedTo: 'Gabriel Smith',
        //   image: '/banner1.jpeg',
        //   logo: '/logo-icon.png',
        //   attachments: 2,
        // },
        // {
        //   id: 76,
        //   title: 'Compliance Review of Vendor Contracts',
        //   dueDate: '2023-12-04',
        //   category: 'Compliance',
        //   status: 'Open',
        //   assignedTo: 'Ella Brown',
        //   image: '/banner2.jpg',
        //   logo: '/logo-icon.png',
        //   attachments: 3,
        // },
        // {
        //   id: 77,
        //   title: 'Assessment of Workplace Safety Programs',
        //   dueDate: '2023-11-12',
        //   category: 'Audit',
        //   status: 'Completed',
        //   assignedTo: 'Jackson Lee',
        //   image: '/banner1.jpeg',
        //   logo: '/logo-icon.png',
        //   attachments: 0,
        // },
        // {
        //   id: 78,
        //   title: 'Review of Safety Data Sheets',
        //   dueDate: '2023-11-27',
        //   category: 'Health & Safety',
        //   status: 'In Progress',
        //   assignedTo: 'Grace Harris',
        //   image: '/banner2.jpg',
        //   logo: '/logo-icon.png',
        //   attachments: 4,
        // },
        // {
        //   id: 79,
        //   title: 'Training on Safety Equipment Use',
        //   dueDate: '2023-11-20',
        //   category: 'Training',
        //   status: 'Open',
        //   assignedTo: 'Oliver Scott',
        //   image: '/banner1.jpeg',
        //   logo: '/logo-icon.png',
        //   attachments: 1,
        // },
        // {
        //   id: 80,
        //   title: 'Emergency Preparedness Training',
        //   dueDate: '2023-12-23',
        //   category: 'Training',
        //   status: 'Drafted',
        //   assignedTo: 'Abigail Lee',
        //   image: '/banner2.jpg',
        //   logo: '/logo-icon.png',
        //   attachments: 2,
        // },
        // {
        //   id: 81,
        //   title: 'Review of Emergency Response Plans',
        //   dueDate: '2023-12-19',
        //   category: 'Health & Safety',
        //   status: 'In Progress',
        //   assignedTo: 'Matthew Thompson',
        //   image: '/banner1.jpeg',
        //   logo: '/logo-icon.png',
        //   attachments: 3,
        // },
        // {
        //   id: 82,
        //   title: 'Assessment of Safety Equipment Inventory',
        //   dueDate: '2023-12-27',
        //   category: 'Maintenance',
        //   status: 'Open',
        //   assignedTo: 'Charlotte Brown',
        //   image: '/banner2.jpg',
        //   logo: '/logo-icon.png',
        //   attachments: 0,
        // },
        // {
        //   id: 83,
        //   title: 'Evaluation of Risk Management Strategies',
        //   dueDate: '2023-12-29',
        //   category: 'Risk Management',
        //   status: 'Drafted',
        //   assignedTo: 'Anthony Robinson',
        //   image: '/banner1.jpeg',
        //   logo: '/logo-icon.png',
        //   attachments: 1,
        // },
        // {
        //   id: 84,
        //   title: 'Quarterly Review of Budget Allocation',
        //   dueDate: '2023-11-26',
        //   category: 'Finance',
        //   status: 'Completed',
        //   assignedTo: 'Ella Scott',
        //   image: '/banner2.jpg',
        //   logo: '/logo-icon.png',
        //   attachments: 2,
        // },
        // {
        //   id: 85,
        //   title: 'Update of Environmental Training Materials',
        //   dueDate: '2023-12-08',
        //   category: 'Training',
        //   status: 'In Progress',
        //   assignedTo: 'Lucas Brown',
        //   image: '/banner1.jpeg',
        //   logo: '/logo-icon.png',
        //   attachments: 3,
        // },
        // {
        //   id: 86,
        //   title: 'Safety Equipment Inspection Schedule',
        //   dueDate: '2023-12-04',
        //   category: 'Maintenance',
        //   status: 'Open',
        //   assignedTo: 'Lily Carter',
        //   image: '/banner2.jpg',
        //   logo: '/logo-icon.png',
        //   attachments: 1,
        // },
        // {
        //   id: 87,
        //   title: 'Assessment of Safety Training Effectiveness',
        //   dueDate: '2023-11-10',
        //   category: 'Training',
        //   status: 'Drafted',
        //   assignedTo: 'Jackson White',
        //   image: '/banner1.jpeg',
        //   logo: '/logo-icon.png',
        //   attachments: 2,
        // },
        // {
        //   id: 88,
        //   title: 'Review of Workplace Incident Response Procedures',
        //   dueDate: '2023-11-28',
        //   category: 'Audit',
        //   status: 'In Progress',
        //   assignedTo: 'Ava Brown',
        //   image: '/banner2.jpg',
        //   logo: '/logo-icon.png',
        //   attachments: 0,
        // },
        // {
        //   id: 89,
        //   title: 'Environmental Impact Assessment',
        //   dueDate: '2023-11-25',
        //   category: 'Environment',
        //   status: 'Open',
        //   assignedTo: 'William Taylor',
        //   image: '/banner1.jpeg',
        //   logo: '/logo-icon.png',
        //   attachments: 4,
        // },
        // {
        //   id: 90,
        //   title: 'Annual Review of Safety Protocols',
        //   dueDate: '2023-12-31',
        //   category: 'Health & Safety',
        //   status: 'In Progress',
        //   assignedTo: 'Aiden Young',
        //   image: '/banner2.jpg',
        //   logo: '/logo-icon.png',
        //   attachments: 3,
        // },
        // {
        //   id: 91,
        //   title: 'Compliance Review of Financial Records',
        //   dueDate: '2023-12-06',
        //   category: 'Compliance',
        //   status: 'Open',
        //   assignedTo: 'James Moore',
        //   image: '/banner1.jpeg',
        //   logo: '/logo-icon.png',
        //   attachments: 1,
        // },
        // {
        //   id: 92,
        //   title: 'Safety Training for New Employees',
        //   dueDate: '2023-12-15',
        //   category: 'Training',
        //   status: 'Drafted',
        //   assignedTo: 'Chloe Anderson',
        //   image: '/banner2.jpg',
        //   logo: '/logo-icon.png',
        //   attachments: 5,
        // },
        // {
        //   id: 93,
        //   title: 'Review of Environmental Procedures',
        //   dueDate: '2023-11-22',
        //   category: 'Audit',
        //   status: 'In Progress',
        //   assignedTo: 'Mason Clark',
        //   image: '/banner1.jpeg',
        //   logo: '/logo-icon.png',
        //   attachments: 0,
        // },
        // {
        //   id: 94,
        //   title: 'Training on Emergency Response Techniques',
        //   dueDate: '2023-12-25',
        //   category: 'Training',
        //   status: 'Open',
        //   assignedTo: 'Zoe Green',
        //   image: '/banner2.jpg',
        //   logo: '/logo-icon.png',
        //   attachments: 3,
        // },
        // {
        //   id: 95,
        //   title: 'Monthly Update on Compliance Issues',
        //   dueDate: '2023-12-29',
        //   category: 'Compliance',
        //   status: 'Drafted',
        //   assignedTo: 'Liam Harris',
        //   image: '/banner1.jpeg',
        //   logo: '/logo-icon.png',
        //   attachments: 1,
        // },
        // {
        //   id: 96,
        //   title: 'Annual Review of Risk Assessment Procedures',
        //   dueDate: '2023-12-15',
        //   category: 'Risk Management',
        //   status: 'In Progress',
        //   assignedTo: 'Amelia Young',
        //   image: '/banner2.jpg',
        //   logo: '/logo-icon.png',
        //   attachments: 0,
        // },
        // {
        //   id: 97,
        //   title: 'Preparation of Safety Audit Reports',
        //   dueDate: '2023-12-20',
        //   category: 'Audit',
        //   status: 'Completed',
        //   assignedTo: 'Caleb Lee',
        //   image: '/banner1.jpeg',
        //   logo: '/logo-icon.png',
        //   attachments: 2,
        // },
        // {
        //   id: 98,
        //   title: 'Environmental Health and Safety Assessment',
        //   dueDate: '2023-12-09',
        //   category: 'Health & Safety',
        //   status: 'In Progress',
        //   assignedTo: 'Lucas Martinez',
        //   image: '/banner2.jpg',
        //   logo: '/logo-icon.png',
        //   attachments: 4,
        // },
        // {
        //   id: 99,
        //   title: 'Annual Review of Financial Compliance',
        //   dueDate: '2023-12-31',
        //   category: 'Finance',
        //   status: 'Open',
        //   assignedTo: 'Isabella Young',
        //   image: '/banner1.jpeg',
        //   logo: '/logo-icon.png',
        //   attachments: 3,
        // },
        // {
        //   id: 100,
        //   title: 'Review of Emergency Management Plans',
        //   dueDate: '2023-12-26',
        //   category: 'Risk Management',
        //   status: 'Drafted',
        //   assignedTo: 'Ava White',
        //   image: '/banner2.jpg',
        //   logo: '/logo-icon.png',
        //   attachments: 1,
        // },
      ]; 

  